### ISSUE TITLE
关于Apistructure 初始化的问题

### ISSUE THREAD

**Issue by hadrianl** [nooperpudd/ctpwrapper#31]
当遇到类型为ctypes.c_char的字段赋值是，如果用默认空值会出现typeerror
p = QryProductField()
Traceback (most recent call last):
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-f636d7ed8b46>", line 1, in <module>
    p = QryProductField()
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\ctpwrapper\ApiStructure.py", line 3119, in __init__
    self.ProductClass = self._to_bytes(ProductClass)
TypeError: one character bytes, bytearray or integer expected

**Comment by hadrianl** [comment]
这个改动有bug，响应回报引用Structure就会crash。。。
