### ISSUE TITLE
one character bytes, bytearray or integer expected

### ISSUE THREAD

**Issue by kennyoysj** [nooperpudd/ctpwrapper#53]
下单时一直报错
`Traceback (most recent call last):
  File "I:\tools\anaconda\envs\insight\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "I:\workspace\py_ctp\py_ctp\new\tradeServer.py", line 140, in run
    self.funcs[action](code=code,action=action)
  File "I:\workspace\py_ctp\py_ctp\new\tradeServer.py", line 155, in longStock
    self.orderInsert(stock, requestN, TThostFtdcDirectionType.THOST_FTDC_D_Buy.value, stock.AskPrice1) # 卖一价
  File "I:\workspace\py_ctp\py_ctp\new\tradeServer.py", line 169, in orderInsert
    orderfield = InputOrderField(self.broker_id,self.investor_id,depthMarketDataField.InstrumentID,UserID=self.user_id,OrderPriceType=b'50')  # type:InputOrderField
  File "I:\tools\anaconda\envs\insight\lib\site-packages\ctpwrapper\ApiStructure.py", line 1634, in __init__
    self.TimeCondition = self._to_bytes(TimeCondition)
TypeError: one character bytes, bytearray or integer expected`

**Comment by kennyoysj** [comment]
各个字段都报错了
难道是我的用法不对

**Comment by kennyoysj** [comment]
弄错了
